#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed May 20 14:12:02 2020

@author: agni
"""
import pyreadstat
import pandas as pd
import datetime
import numpy as np
import pickle



#pathfull = '../../../Dropbox (Personal)/COVID_clinical/covid19_hope/IVAN J NUNEZ GIL - HOPEDATABASE 5.5.20V3.8AGNI.sav'
pathfull = '../../../Dropbox (Personal)/COVID_clinical/covid19_hope/HOPEDATABASE 5.5.20V3.9AGNI.sav'

path  = '../../../Dropbox (Personal)/COVID_clinical/covid19_hope'
df, meta = pyreadstat.read_sav(pathfull)
df.to_csv(path+'/hope_data.csv')


path  = '../../../Dropbox (Personal)/COVID_clinical/covid19_hope'
# Load admission info
df = pd.read_csv('%s/hope_data.csv' % path, sep=',' )
   
#Split columns in categories
LOCATION = ['INV_HOSPITAL1','INV_COUNTRY1']

DEMOGRAPHICS = ['CO_GENDER','CO_RACE','PREGNANT','VL_WEIGHT','VL_HEIGHT', 'EDAD']

COMORBIDITIES = ['CO_DM', 'INDM', 'IN_HYPERTENSION', 'IN_DISPLEMIA', 'IN_OBESITY',
                 'CO_CURRENTSMOKER', 'IN_TABACONUMERICO', 'IN_TABACOSIONO',
                 'IN_RENALINSUF','IN_ANYLUNGDISEASE', 'AF', 'VIH', 'TBPASSED', 'IN_ANYHEARTDISEASE',
                 'CO_MAINHEARTDISEASE',
                 'IN_ANYCEREBROVASCULARDISEASE', 'IN_CONECTIVEDISEASE',
                 'IN_LIVER_DISEASE', 'IN_ANYCANCER', 'CO_TYPEOFCANCER']

OTHER = ['ANYDRUGALLERGY','DS_KNOWNALLERGIES']

DRUGS_ADMISSIONS = ['IN_HOME_OXIGEN_THERAPY', 'IN_PREVIOUSASPIRIN', 'IN_OTHERANTIPLATELET',
       'IN_ORALANTICOAGL', 'IN_ORALANTICOAGL_TYPE',
       'CO_ORALANTICOAGL_TYPE_OAC', 'IN_ACEI_ARB', 'IN_BETABLOCKERS',
       'IN_BETAGONISTINHALED', 'IN_GLUCORTICOIDSINHALED',
       'IN_DVITAMINSUPLEMENT','IN_BENZODIACEPINES', 'IN_ANTIDEPRESSANT', 'DS_OTHERPREVIOUSTREATMENT']

COVID_DRUGS = ['IN_USEOFCORTICOIDSDURINGADMISSION',
       'IN_USEOFCLOROQUINEORSIMILARDURINGADMISSION',
       'IN_USEOFANTIVIRALDRUGSDURINGADMISSION',
       'IN_USEOFINTERFERONORSIMILARDURINGADMISSION',
       'IN_USEOFTOCILIZUMABORSIMILARDURINGADMISSION', 'IN_USEOFANTIBIOTICS',
       'IN_ACEI_ARBS_DURING_HOSPITAL_STAY', 'IN_ANTICOAGLDURINGADMISSION',
       'CO_MAIN_ANTICOAGULATION_INHOSPITAL_STAY',
       'DT_USE_CLOROQUINE2', 'DT_USE_ANTIVIRAL_DRUGS2',
       'DT_USE_TOCILIZUMAB2']

DISCHARGE_DRUGS = ['IN_DISCHARGEANTIPLATELET','IN_DISCHARGEACEI', 'IN_DISCHARGEANTICOAGU',
       'DS_DISCHARGEMEDS']


SYMPTOMS = ['IN_ASYMPTOMATIC', 'CO_DISPNEA', 'IN_TAQUIPNEA', 'IN_FATIGUE',
            'IN_HIPO_ANOSMIA', 'IN_DISGEUSIA', 'IN_SORETHROAT','VL_MAXTEMPDURINGADMISSION', 
            'IN_COUGH', 'IN_VOMITING', 'IN_DIARRHEA',
            'IN_MYALGIAORARTHALGIA']

BINARY_LABS_VITALS_ADMISSION = ['IN_02SAT_92', 'IN_ELEVATEDDDIMER',
       'IN_ELEVATEDPROCALCITONIN', 'IN_ELEVATEDPCR', 'IN_ELEVATEDTN',
       'IN_ELEVATEDTRANSAMINASES', 'IN_ELEVATED_FERRITINE',
       'IN_ELEVATED_TRIGLYCERIDES', 'IN_ELEVATED_LDH','IN_CRELEVADA1.5OMAS',
       'IN_LEUCOS4000OMENOS','IN_LINFOS1500OMENOS','IN_HB12OMENOS',
       'IN_PLAQTS150000OMENOS','IN_BLOOD_PRESSURE_ABNORMAL']

CONTINUE_LABS_ADMISSION = ['VL_ONSETCREATININELEVELS','VL_ONSETARTERIALBLOODGASPH',
       'VL_ONSETARTERIALBLOODGASPA02', 'VL_ONSETARTERIALBLOODGASPAC02',
       'LV_ONSETARTERIALBLOODGAS02SATURATION','VL_ONSET_NA_LEVELS',
       'VL_TOTAL_ONSET_LEUCOCYTES_COUNT', 'VL_TOTAL_ONSET_LINPHOCYTES_COUNT',
        'VL_ONSET_HEMOGLOBIN','VL_TOTAL_ONSET_PLATELET_COUNT',
        'VL_GLASGOW_COMA_SCORE']

XRAY_RESULTS=['CO_ANYCHESTRXABNORMALITY','DS_OTHERRELEVANTFINDINGS']

PROCEDURES = ['IN_02DURINGADMISSION', 'IN_HIGHFLOWNASALCANNULA',
       'IN_NOINVASIVEMECHANICALVENTILATION',
       'IN_INVASIVEMECHANICALVENTILATION', 'NU_DAYSONMECHANICALVENTILATION',
       'IN_PRONEDURINGADMISSION', 'IN_CIRCULATORYORECMOSUPPORT',
       'IN_ECMO_SIMILAR_SUPPORT']


OUTCOMES = ['IN_ICUADMISSION','IN_RESPIRATORYINSUFFICIENCYADMISSION',
       'IN_HEARTFAILUREADMISSION', 'IN_RENALFAILURE',
       'IN_UPPERRESPIRAROTYTRACTINFECTIONDATA', 'CO_PNEUMONIA', 'IN_PNEUMONIA',
       'IN_SEPSIS', 'IN_SYSTEMICINFLAMATORYREPONSESYNDROME',
       'IN_ANYRELEVANTBLEEDING', 'IN_HEMOPTYSIS', 'IN_EMBOLICEVENT',
       'DS_COMPLICATIONSDESCRIPTION', 'IN_RAS_CUTANEOUS_INVOLVEMENT',
       'CO_DEATHCAUSE', 'DEATH','CO_DISCHARGETO','FOLLOWUPDAYSKM', 'DIASAMUERTEOUCI',
       'IN_MUERTEOUCI']

DATES = ['DT_BORN2', 'DT_ONSETSYMPTOMS2',
       'DT_HOSPITAL_ADMISSION2', 'DT_ADMISSION_ICU2',
       'DT_ICUDISCHARGE2', 'DT_DISCHARGE2',
       'DT_LASTFOLLOWUPDATE2','DT_DEATHORICU', 'DT_DEATH2',
       'DT_TEST_COVID2']

df.groupby(COVID_DRUGS).size()


df['ANTICOAG'] = df['IN_ANTICOAGLDURINGADMISSION']
df['ANTICOAG'][df['ANTICOAG']>1] = 1

treat = df.groupby(['IN_USEOFCLOROQUINEORSIMILARDURINGADMISSION',
           'IN_USEOFANTIVIRALDRUGSDURINGADMISSION','ANTICOAG']).size()

covid_info = df[COVID_DRUGS].describe()
proc_info = df[PROCEDURES].describe()


